# ----
# Site

title: Irish Baking
url: "https://irishbaking.ie/"
baseurl:
google_analytics_key:
newsletter_action:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Irish Baking food blog.
author:
  name:
  email: mcginleyireland@gmail.com
  twitter: # twitter username without the @ symbol
social:
  name: Irish Baking
  links:
    - https://irishbaking.ie/

# -----
# Build

timezone: Etc/UTC

paginate: 10
paginate_path: "/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      push_sidebar_down: true
      print_stylesheet: true
      comments: true
      _options:
        content:
          width: 1560
          height: 2000
        featured_image:
          width: 1560
          height: 2000
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true
  -
    scope:
      path: ".well-known/brave-rewards-verification.txt"
    values:
      layout: "default"
      push_sidebar_down: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

include:
  - .well-known/brave-rewards-verification.txt

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:
  - Instagram


_options:
  author_image:
    width: 400
    height: 400
